[location]
# TODO: aggiornare quando GMP343 sara' deployato a Cimone
# (al momento la sonda e' nello shelter Bologna, vedi site.bo-shelter.ini)
name = CMN
latitude = 44.193
longitude = 10.701
timezone = UTC
# altitude = 2165m (Cimone GAW station)
